Started by user R3tr1c
[Pipeline] Start of Pipeline
[Pipeline] node
Running on Jenkins in /root/.jenkins/workspace/TestPipe
[Pipeline] {
[Pipeline] withEnv
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Preparation)
[Pipeline] echo
Preparing the environment...
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Get Secret)
[Pipeline] script
[Pipeline] {
[Pipeline] withVault
WARNING: Unknown parameter(s) found for class type 'com.datapipe.jenkins.vault.VaultBindingStep': engineVersion,vaultAddr,vaultCredentialId
[Pipeline] }
[Pipeline] // script
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Use Secret)
Stage "Use Secret" skipped due to earlier failure(s)
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Post-processing)
Stage "Post-processing" skipped due to earlier failure(s)
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
Also:   org.jenkinsci.plugins.workflow.actions.ErrorAction$ErrorId: 0cbe48b8-b37e-45b8-8320-cd9de5314399
com.cloudbees.plugins.credentials.CredentialsUnavailableException: Property 'my-vault-token' is currently unavailable
	at com.datapipe.jenkins.vault.VaultAccessor.retrieveVaultCredentials(VaultAccessor.java:255)
	at com.datapipe.jenkins.vault.VaultAccessor.retrieveVaultSecrets(VaultAccessor.java:188)
	at com.datapipe.jenkins.vault.VaultBindingStep$Execution.doStart(VaultBindingStep.java:115)
	at org.jenkinsci.plugins.workflow.steps.GeneralNonBlockingStepExecution.lambda$run$0(GeneralNonBlockingStepExecution.java:77)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Finished: FAILURE
